openapi: "3.0.3"
info:
  title: "arbeidssoker_besvarelse API"
  description: "arbeidssoker_besvarelse API"
  version: "1.0.0"
servers:
- url: "https://arbeidssoker_besvarelse"
paths:
  /api/v1/besvarelse:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ArbeidssokerRegistrertResponse"
  /api/v1/besvarelse/situasjon:
    patch:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ArbeidssokerRegistrertResponse"
  /internal/isAlive:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "ALIVE"
  /internal/isReady:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "READY"
  /internal/metrics:
    get:
      description: ""
      parameters:
      - name: "name[]"
        in: "query"
        required: false
        schema:
          type: "string"
components:
  schemas:
    Besvarelse:
      type: "object"
      properties:
        utdanning:
          type: "string"
          enum:
          - "INGEN_UTDANNING"
          - "GRUNNSKOLE"
          - "VIDEREGAENDE_GRUNNUTDANNING"
          - "VIDEREGAENDE_FAGBREV_SVENNEBREV"
          - "HOYERE_UTDANNING_1_TIL_4"
          - "HOYERE_UTDANNING_5_ELLER_MER"
          - "INGEN_SVAR"
        utdanningBestatt:
          type: "string"
          enum:
          - "JA"
          - "NEI"
          - "INGEN_SVAR"
        utdanningGodkjent:
          type: "string"
          enum:
          - "JA"
          - "NEI"
          - "VET_IKKE"
          - "INGEN_SVAR"
        helseHinder:
          type: "string"
          enum:
          - "JA"
          - "NEI"
          - "INGEN_SVAR"
        andreForhold:
          type: "string"
          enum:
          - "JA"
          - "NEI"
          - "INGEN_SVAR"
        sisteStilling:
          type: "string"
          enum:
          - "HAR_HATT_JOBB"
          - "HAR_IKKE_HATT_JOBB"
          - "INGEN_SVAR"
        dinSituasjon:
          type: "string"
          enum:
          - "MISTET_JOBBEN"
          - "ALDRI_HATT_JOBB"
          - "HAR_SAGT_OPP"
          - "VIL_BYTTE_JOBB"
          - "ER_PERMITTERT"
          - "USIKKER_JOBBSITUASJON"
          - "JOBB_OVER_2_AAR"
          - "VIL_FORTSETTE_I_JOBB"
          - "AKKURAT_FULLFORT_UTDANNING"
          - "DELTIDSJOBB_VIL_MER"
        fremtidigSituasjon:
          type: "string"
          enum:
          - "SAMME_ARBEIDSGIVER"
          - "SAMME_ARBEIDSGIVER_NY_STILLING"
          - "NY_ARBEIDSGIVER"
          - "USIKKER"
          - "INGEN_PASSER"
        tilbakeIArbeid:
          type: "string"
          enum:
          - "JA_FULL_STILLING"
          - "JA_REDUSERT_STILLING"
          - "USIKKER"
          - "NEI"
    ArbeidssokerRegistrertResponse:
      type: "object"
      properties:
        registreringsId:
          type: "integer"
          format: "int32"
        besvarelse:
          $ref: "#/components/schemas/Besvarelse"
        opprettet:
          type: "string"
          format: "date-time"
        endretAv:
          type: "string"