openapi: "3.0.3"
info:
  title: "arbeidssoker_besvarelse API"
  description: "arbeidssoker_besvarelse API"
  version: "1.0.0"
servers:
- url: "https://arbeidssoker_besvarelse"
paths:
  /api/v1/besvarelse:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ArbeidssokerRegistrertResponse"
  /api/v1/besvarelse/situasjon:
    post:
      description: ""
      requestBody:
        content:
          '*/*':
            schema:
              $ref: "#/components/schemas/EndreSituasjonRequest"
        required: true
      responses:
        "201":
          description: "Created"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ArbeidssokerRegistrertResponse"
  /api/v1/veileder/besvarelse:
    post:
      description: ""
      requestBody:
        content:
          '*/*':
            schema:
              $ref: "#/components/schemas/VeilederRequest"
        required: true
      responses:
        "403":
          description: "Forbidden"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "NAV-ansatt har ikke tilgang"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ArbeidssokerRegistrertResponse"
  /api/v1/veileder/har-tilgang:
    post:
      description: ""
      requestBody:
        content:
          '*/*':
            schema:
              $ref: "#/components/schemas/VeilederRequest"
        required: true
      responses:
        "403":
          description: "Forbidden"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "NAV-ansatt har ikke tilgang"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "NAV-ansatt har tilgang"
  /internal/isAlive:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "ALIVE"
  /internal/isReady:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "READY"
  /internal/metrics:
    get:
      description: ""
      parameters:
      - name: "name[]"
        in: "query"
        required: false
        schema:
          type: "array"
          items:
            type: "string"
components:
  schemas:
    Utdanning:
      type: "object"
      properties:
        verdi:
          type: "string"
          enum:
          - "INGEN_UTDANNING"
          - "GRUNNSKOLE"
          - "VIDEREGAENDE_GRUNNUTDANNING"
          - "VIDEREGAENDE_FAGBREV_SVENNEBREV"
          - "HOYERE_UTDANNING_1_TIL_4"
          - "HOYERE_UTDANNING_5_ELLER_MER"
          - "INGEN_SVAR"
        gjelderFraDato:
          type: "string"
          format: "date"
        gjelderTilDato:
          type: "string"
          format: "date"
        endretAv:
          type: "string"
          enum:
          - "BRUKER"
          - "VEILEDER"
          - "SYSTEM"
        endretTidspunkt:
          type: "string"
          format: "date-time"
    UtdanningBestatt:
      type: "object"
      properties:
        verdi:
          type: "string"
          enum:
          - "JA"
          - "NEI"
          - "INGEN_SVAR"
        gjelderFraDato:
          type: "string"
          format: "date"
        gjelderTilDato:
          type: "string"
          format: "date"
        endretAv:
          type: "string"
          enum:
          - "BRUKER"
          - "VEILEDER"
          - "SYSTEM"
        endretTidspunkt:
          type: "string"
          format: "date-time"
    UtdanningGodkjent:
      type: "object"
      properties:
        verdi:
          type: "string"
          enum:
          - "JA"
          - "NEI"
          - "VET_IKKE"
          - "INGEN_SVAR"
        gjelderFraDato:
          type: "string"
          format: "date"
        gjelderTilDato:
          type: "string"
          format: "date"
        endretAv:
          type: "string"
          enum:
          - "BRUKER"
          - "VEILEDER"
          - "SYSTEM"
        endretTidspunkt:
          type: "string"
          format: "date-time"
    HelseHinder:
      type: "object"
      properties:
        verdi:
          type: "string"
          enum:
          - "JA"
          - "NEI"
          - "INGEN_SVAR"
        gjelderFraDato:
          type: "string"
          format: "date"
        gjelderTilDato:
          type: "string"
          format: "date"
        endretAv:
          type: "string"
          enum:
          - "BRUKER"
          - "VEILEDER"
          - "SYSTEM"
        endretTidspunkt:
          type: "string"
          format: "date-time"
    AndreForhold:
      type: "object"
      properties:
        verdi:
          type: "string"
          enum:
          - "JA"
          - "NEI"
          - "INGEN_SVAR"
        gjelderFraDato:
          type: "string"
          format: "date"
        gjelderTilDato:
          type: "string"
          format: "date"
        endretAv:
          type: "string"
          enum:
          - "BRUKER"
          - "VEILEDER"
          - "SYSTEM"
        endretTidspunkt:
          type: "string"
          format: "date-time"
    SisteStilling:
      type: "object"
      properties:
        verdi:
          type: "string"
          enum:
          - "HAR_HATT_JOBB"
          - "HAR_IKKE_HATT_JOBB"
          - "INGEN_SVAR"
        gjelderFraDato:
          type: "string"
          format: "date"
        gjelderTilDato:
          type: "string"
          format: "date"
        endretAv:
          type: "string"
          enum:
          - "BRUKER"
          - "VEILEDER"
          - "SYSTEM"
        endretTidspunkt:
          type: "string"
          format: "date-time"
    DinSituasjonTilleggsData:
      type: "object"
      properties:
        forsteArbeidsdagDato:
          type: "string"
          format: "date"
        sisteArbeidsdagDato:
          type: "string"
          format: "date"
        oppsigelseDato:
          type: "string"
          format: "date"
        gjelderFraDato:
          type: "string"
          format: "date"
        permitteringsProsent:
          type: "string"
        stillingsProsent:
          type: "string"
        permitteringForlenget:
          type: "string"
        harNyJobb:
          type: "string"
    DinSituasjon:
      type: "object"
      properties:
        verdi:
          type: "string"
          enum:
          - "MISTET_JOBBEN"
          - "ALDRI_HATT_JOBB"
          - "HAR_SAGT_OPP"
          - "VIL_BYTTE_JOBB"
          - "ER_PERMITTERT"
          - "USIKKER_JOBBSITUASJON"
          - "JOBB_OVER_2_AAR"
          - "VIL_FORTSETTE_I_JOBB"
          - "AKKURAT_FULLFORT_UTDANNING"
          - "DELTIDSJOBB_VIL_MER"
          - "OPPSIGELSE"
          - "ENDRET_PERMITTERINGSPROSENT"
          - "TILBAKE_TIL_JOBB"
          - "NY_JOBB"
          - "MIDLERTIDIG_JOBB"
          - "KONKURS"
          - "UAVKLART"
          - "ANNET"
        tilleggsData:
          $ref: "#/components/schemas/DinSituasjonTilleggsData"
        gjelderFraDato:
          type: "string"
          format: "date"
        gjelderTilDato:
          type: "string"
          format: "date"
        endretAv:
          type: "string"
          enum:
          - "BRUKER"
          - "VEILEDER"
          - "SYSTEM"
        endretTidspunkt:
          type: "string"
          format: "date-time"
    FremtidigSituasjon:
      type: "object"
      properties:
        verdi:
          type: "string"
          enum:
          - "SAMME_ARBEIDSGIVER"
          - "SAMME_ARBEIDSGIVER_NY_STILLING"
          - "NY_ARBEIDSGIVER"
          - "USIKKER"
          - "INGEN_PASSER"
        gjelderFraDato:
          type: "string"
          format: "date"
        gjelderTilDato:
          type: "string"
          format: "date"
        endretAv:
          type: "string"
          enum:
          - "BRUKER"
          - "VEILEDER"
          - "SYSTEM"
        endretTidspunkt:
          type: "string"
          format: "date-time"
    TilbakeIArbeid:
      type: "object"
      properties:
        verdi:
          type: "string"
          enum:
          - "JA_FULL_STILLING"
          - "JA_REDUSERT_STILLING"
          - "USIKKER"
          - "NEI"
        gjelderFraDato:
          type: "string"
          format: "date"
        gjelderTilDato:
          type: "string"
          format: "date"
        endretAv:
          type: "string"
          enum:
          - "BRUKER"
          - "VEILEDER"
          - "SYSTEM"
        endretTidspunkt:
          type: "string"
          format: "date-time"
    Besvarelse:
      type: "object"
      properties:
        utdanning:
          $ref: "#/components/schemas/Utdanning"
        utdanningBestatt:
          $ref: "#/components/schemas/UtdanningBestatt"
        utdanningGodkjent:
          $ref: "#/components/schemas/UtdanningGodkjent"
        helseHinder:
          $ref: "#/components/schemas/HelseHinder"
        andreForhold:
          $ref: "#/components/schemas/AndreForhold"
        sisteStilling:
          $ref: "#/components/schemas/SisteStilling"
        dinSituasjon:
          $ref: "#/components/schemas/DinSituasjon"
        fremtidigSituasjon:
          $ref: "#/components/schemas/FremtidigSituasjon"
        tilbakeIArbeid:
          $ref: "#/components/schemas/TilbakeIArbeid"
    ArbeidssokerRegistrertResponse:
      type: "object"
      properties:
        registreringsId:
          type: "integer"
          format: "int32"
        besvarelse:
          $ref: "#/components/schemas/Besvarelse"
        endretAv:
          type: "string"
          enum:
          - "BRUKER"
          - "VEILEDER"
          - "SYSTEM"
        endretTidspunkt:
          type: "string"
          format: "date-time"
        registreringsTidspunkt:
          type: "string"
          format: "date-time"
        opprettetAv:
          type: "string"
          enum:
          - "BRUKER"
          - "VEILEDER"
          - "SYSTEM"
        erBesvarelsenEndret:
          type: "boolean"
    EndreSituasjonRequest:
      type: "object"
      properties:
        dinSituasjon:
          $ref: "#/components/schemas/DinSituasjon"
    VeilederRequest:
      type: "object"
      properties:
        foedselsnummer:
          type: "string"