apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: paw-arbeidssoker-besvarelse
  namespace: paw
  labels:
    team: paw
spec:
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - NAVident
  secureLogs:
    enabled: true
  image: {{ image }}
  ingresses:
    - https://arbeidssoker-besvarelse.intern.dev.nav.no
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: /internal/isAlive
    initialDelay: 10
  readiness:
    path: /internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /internal/metrics
  env:
    - name: KAFKA_CONSUMER_ARBEIDSSOKER_REGISTERING_TOPIC
      value: paw.arbeidssoker-registrert-v2
    - name: KAFKA_CONSUMER_GROUP_ID
      value: arbeidssoker-besvarelse-consumer-v1
    - name: KAFKA_PRODUCER_ARBEIDSSOKER_BESVARELSE_TOPIC
      value: paw.arbeidssoker-besvarelse-v2
    - name: KAFKA_PRODUCER_ID
      value: arbeidssoker-besvarelse-producer-v1
    - name: PDL_URL
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: PDL_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default
    - name: POAO_TILGANG_CLIENT_URL
      value: http://poao-tilgang.poao.svc.cluster.local
    - name: POAO_TILGANG_CLIENT_SCOPE
      value: api://dev-gcp.poao.poao-tilgang/.default
    - name: OTEL_METRICS_EXPORTER
      value: "none"
  resources:
    limits:
      cpu: 1000m
      memory: 768Mi
    requests:
      cpu: 50m
      memory: 500Mi
  kafka:
    pool: nav-dev
  tokenx:
    enabled: true
  observability:
    tracing:
      enabled: true
  accessPolicy:
      inbound:
        rules:
          - application: aia-backend
            namespace: paw
          - application: arbeidssokerregistrering-for-veileder
          - application: debug-dings
            namespace: plattformsikkerhet
          - application: azure-token-generator
            namespace: aura
            cluster: dev-gcp
          - application: tokenx-token-generator
            namespace: aura
            cluster: dev-gcp
          - application: veilarbvedtaksstotte
            namespace: pto
            cluster: dev-fss
           - application: veilarbvedtaksstotte
            namespace: obo
            cluster: dev-gcp
          - application: veilarbperson
            namespace: pto
            cluster: dev-fss
      outbound:
        rules:
          - application: poao-tilgang
            namespace: poao
        external:
          - host: pdl-api.dev-fss-pub.nais.io
  gcp:
    sqlInstances:
      - type: POSTGRES_14
        databases:
          - name: arbeidssoker-registrert
